### ISSUE TITLE
Deploying a complete system locally

### ISSUE THREAD

**Issue by neischlah** [eclipse-tractusx/digital-product-pass#11]
Hi everyone!

I'm trying to set up a local deployment on my machine. Unfortunately I'm stuck. Please feel free to redirect me if this is the wrong place to ask for help on that.
My goal is to have a local Catena-X network with the digital product pass running, including some initial data, so that I can develop a data provider for it.

## Deployment Questions

1. Which document(s) do I need to follow to get all components needed for a local deployment? [This diagram](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/GETTING-STARTED.md#application-infrastructure) seems to summarize all needed components. Is it complete? E.g. I am missing Keycloak here (in case it is actually required).
2. Is there a helm chart or docker compose with which can deploy all required components or do I need to find and deploy them myself?
3. Can I reuse the [Minimum Viable Dataspace](https://github.com/eclipse-edc/MinimumViableDataspace) somehow, or how is it related?
4. Is there a reason why helm charts are located in two different directories? `deployment/helm/` vs. `charts/`
5. Following [this documentation](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/GETTING-STARTED.md), I managed to set up a HashiCorp Vault. Running `set_dev_values.sh` is returning a 403, probably because the requested path does not exist as the vault is empty. How do I initialize it? I couldn't find this info in the seemingly most relevant [document](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/SECRETS_MANAGEMENT.md).

## Documentation

While there are many documents included, I have a hard time finding the relevant ones. Have you thought about splitting the table listing all relevant documents for different stakeholders like this:

- End User Manual
- Architecture and Concepts
- Local Deployment
- Remote Deployment
- Development and Contributing

## Smaller Issues

1. In [GETTING_STARTED.md](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/GETTING-STARTED.md#application-infrastructure) the repo behind the link [ghcr.io/catenax-ng/catenax-at-home/registry](https://github.com/catenax-ng/catenax-at-home/blob/main/getting-started-guide/docker-compose.yml#L89) is marked as deprecated.
2. Many diagrams in [Arc42](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/arc42/Arc42.md) have a low resolution and are hard to read.

Thanks for your help!

**Comment by matbmoser** [comment]
Hi @neischlah, thank you for opening this issue :)  

Sorry for taking so much time to answer, the reason is because we have no process yet that says how we should handle the issues. However here I am to give you a bit of clarification at least 👍🏻 

As you probably know we are still in the **beta phase** (our product is not market ready yet), so at the moment to deploy the application locally and its architecture is still a bit complicated. But don't worry we will continue to work on that ;)

Some recent steps were that in our latest release [v0.6.0](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v0.6.0) we improved the [documentation](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/GETTING-STARTED.md) related with the **diagrams resolutions**.


In the next releases for example in this upcoming PR #27, we have refactored the documentation and made it more easy to understand, specially by adding a readme at the docs folder to guide you into our documentation. Additionally we also updated the End User Manual, the Deployment Manual, and our Arc42 Documentation.

We will continue to keep you informed from updates 😄, so don't loose track of our product releases 💯  

Now the answer to your questions:
 -  _Which document(s) do I need to follow to get all components needed for a local deployment?_ 
    -   Follow the [GETTING-STARTED.md](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/GETTING-STARTED.md), once the new release v0.7.0 is live (#22, #23, #26 , #27), deploying the app will be more easy, since there will be one single helm chart.
   
-  _Can I reuse the [Minimum Viable Dataspace](https://github.com/eclipse-edc/MinimumViableDataspace) somehow, or how is it related?_
   - Following the Catena-X Architecture we are currently using a forked version of the [EDC Connector](https://github.com/eclipse-edc/Connector), you can find it here in [Tractus-X EDC](https://github.com/eclipse-tractusx/tractusx-edc). So I am not sure if it complies with the Network.
   
- _Is there a reason why helm charts are located in two different directories? deployment/helm/ vs. charts/_:
  - Yes there is a significative reason.
       - `charts/`: Product Released Helm Charts are included here. This means that we are responsible for maintaining the software released here, and that every single version of our application that is released shall contain a deployable version. So here you can find the backend and the frontend from the application.
       - `deployment/helm`: As you probably know now, we use the EDC Connector as Gateaway for the Catena-X network, therefore we provide a helm chart example and test data for you too deploy your own EDC Consumer and EDC Provider components. Using this two components you will be able to test the application workflow and deploy your own assets. 

> **Note**: If you want to consume data from the network you need to be onboarded as company at the Catena-X Network, because there is a number of **protected shared services (IAM, DAPS, Digital Twin Registry)** that allow the companies to build, maintain and control the ecosystem. If you want more info go to: https://eclipse-tractusx.github.io/aboutus or https://catena-x.net/en/catena-x-introduce-implement/onboarding

- _About the HashiCorpVault Issue_:
  - We don't provide any template (just an example) on how to create your secret on the Vault. If you follow the [deployment documentation](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/deployment/README.md) you will see that everything needs to be at the moment configured in a ArgoCD instance. This means that there need to be some sort of plugin that manages the secrets for you and injects them in the application at the [deployment helm values](https://github.com/eclipse-tractusx/digital-product-pass/blob/104b7dcb9787dedaa68606c3cd983d0dec122414/charts/consumer-ui/values-int.yaml#LL43C1-L47C61) for each environment.
 - _Another thing that maybe is also from your interest_: If you want to run the system locally, you need to first **deploy a local Keycloak Instance**  and use our [test realm](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docker/local/Keycloak/realm.json) in Keycloak to run the application. You can follow [this guideline](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docker/local/Keycloak/README.md) for doing that 💯 



@neischlah I hoped this helped you to understand a bit better the application ✅ 
Thanks for your feedback, like this we improve and get better and better 🥇 

Keep track of our new releases and stay tuned 🤩 for the official Catena-X releases in the Tractus-X KITs: [https://eclipse-tractusx.github.io/developer](https://eclipse-tractusx.github.io/developer). 

This application will also be part of a KIT (as all the Catena-X Products), the only thing we ask you is a bit of patience 😉, soon we will be market ready and you will be able to improve your business process with it 😍 [#WeAreOpenForBusiness](https://catena-x.net/en/vision-goals)

If you need anything more please feel free to ask, otherwise I would say that this issue is ready to be closed, since no more action is needed... ✔️
