### ISSUE TITLE
Catena-X Portal Access (need credentials to test backend)

### ISSUE THREAD

**Issue by hillgach** [eclipse-tractusx/digital-product-pass#174]
Hi team,

I would like to start the backend provided on this project. I need to enter in the vault valid credentials from the Catena-X portal. Can you please grant me access in order to be able to create my credentials (or provide me the credentials)

Regards
Hilario

**Comment by matbmoser** [comment]
Hi @hillgach! Thank you for opening this issue!

First of all for obtaining Catena-X credentials your company needs to be onboarded in the Catena-X Network you can find more information here: 
We from the Digital Product Pass team can not do that for you and unfortunately the credentials for the Demo Catena-X Portal are not public and are reserved for Consortia Members of Catena-X. 
Other options involves taking part of the Cofinity-X Catena-X Network (https://www.cofinity-x.com/) the first operated pre productive and productive network. If you are onboarded there, you will be able to set up the backend and use the EDC connectors to do the contract negotiations and retrieve data from other companies.

## Options you have
Other options for you that just wants to test the backend.
- If you have already SSI credentials for your up and running in your EDC, then use the same credentials in the backend as tech user.
- Another option is to use your own Keycloak to login in the application. You can configure it using this realm config file: 
https://github.com/eclipse-tractusx/digital-product-pass/blob/06c810df4dfbba98d0b957968188c37bfbdfc568/docker/local/Keycloak/realm.json 
    - If you need help just follow this readme: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docker/local/Keycloak/README.md
    

## Important Clarifications
- The backend needs to be connected to a valid EDC connector to work (otherwise the backend will just give an error saying that the EDC is not reachable)
    - The SSI credentials from the EDC needs to be valid and generated in the portal (thats a self service thing, if you have access to the portal, is just to create the credentials).
- If you want to deploy the hole Catena-X Network for testing you can use the MXD, and create your own portal credentials I would recommend you to start here: https://github.com/eclipse-tractusx/tutorial-resources/tree/main/mxd

I hope this helped you to understand, or at least has given you a way forward.

If you need anything else or did not understood something, feel free to ask :)

**Comment by matbmoser** [comment]
I will close this issue since I see no further action from our side.
