### ISSUE TITLE
Enduser installation instructions not sufficient

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/digital-product-pass#31]
Available installation instructions describe the installation from a developer point of view (using minikube) but not from a end user perspective. End users won't operate DPP using minikube in production.

The Deployment as well as the Getting Started guide is referencing the Catena-X Demo infrastructure (ArgoCD, Vault) as prerequisites but outside Catena-X consortia no one will have access to these infrastructure and after consortia phase has ended the infrastructure will be potentially unavailable.

Demo [Helm Charts](https://github.com/eclipse-tractusx/digital-product-pass/tree/main/deployment/helm/) for `edc-*` referencing Catena-X NG EDC repository, but Eclipse-TractusX repositories should be used.

Catenax-at-home is suggested although it has been deprecated.

Please provide installation instruction/documentation for endusers. Consider to distiguish between Enduser and Developer documentation. Currently available documentation is focused on local installation, consortia and developers.

**Comment by matbmoser** [comment]
Hi @carslen! Thank you for creating this issue, is really helpful :)

We are aware that our documentation is not 100% production ready yet. At the moment in a ongoing process to upgrade that and make it easily for the end user to install our application. There was also another issue related with that (#11) which helped us already to improve from what was available before. 

This month we will be catching up and complying with the latest TRGs since we want to be part of release 3.2 (I will enforce that). As a note we were only part of release 3.0 and at that time we complied with all mandatory TRGs for release (v0.4.6).   

Thank your again for raising this points, they need to be fixed!
Soon the DPP will be ready for release 3.2 💯  

We will keep you informed in this issue about our updates related to your points.

**Comment by matbmoser** [comment]
Hi @carslen! 
In our latest stable release [v1.0.0](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v1.0.0) we included the [`Install.md`](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/INSTALL.md) file and refactored the documentation that was not compliant. Additionally the rest of documentation is being reviewed for Quality Gates. 

We thank you again for opening this issue and improving our application quality!

I will be closing this issue if is not a problem for you so that we have it archived ;)

Best Regards,
DPP Team
