### ISSUE TITLE
TRG 7.07 / TRG 7.08: Please provide information for images in documentation

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/digital-product-pass#399]
### Current Behavior

Self-created content does not explictly reference the license. Example: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/interoperability/media/graphBusinessProblem.svg 
- not mentioned in overall NOTICE.md
- no .license file next to it
- overall license information has been included in the repo (LICENSE_non_code)

### Expected Behavior

Following [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#self-created-content) one should license self-created images with CC-BY 4.0. It links to [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08#self-created-content) that proposes to place the license file directly next to it with {same name with file extension}.license.

**Comment by matbmoser** [comment]
Hi @tom-rm-meyer-ISST,

Thank you for creating the ticket! Our Application is no KIT as you may know: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08/#self-created-content. The .md file mentions already the Notice https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/interoperability/InteroperabilityGuide.md#notice

Note that the TRG is for KITs, not for product repositories.

I understand that the .license is something important, and I have used this already in other parts of the repo also, since its a good practice, example: https://github.com/eclipse-tractusx/digital-product-pass/tree/main/dpp-verification/resources/implementation


If the TRG is not really clear and you want to propose that all the repos should have that, go ahead and I will support that, I also think is a good practices, however right now its not enforced for product repositories.

**Comment by tom-rm-meyer-ISST** [comment]
> Hi @tom-rm-meyer-ISST,
> 
> Thank you for creating the ticket! Our Application is no KIT as you may know: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08/#self-created-content. The .md file mentions already the Notice https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/interoperability/InteroperabilityGuide.md#notice
> 
> Note that the TRG is for KITs, not for product repositories.
> 
> I understand that the .license is something important, and I have used this already in other parts of the repo also, since its a good practice, example: https://github.com/eclipse-tractusx/digital-product-pass/tree/main/dpp-verification/resources/implementation
> 
> If the TRG is not really clear and you want to propose that all the repos should have that, go ahead and I will support that, I also think is a good practice, however right now its not enforced for product repositories.

Ah, missed to check that notice file!

Regarding TRG 7.08: It's linked from TRG 7.07 with 
_"Self-created content like images should have the copyright and license information included, where ever possible. Images should go under the CC-BY-4.0. See [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08#self-created-content)"._ 

Thus, the handling should be the same for applications.

Maybe we should discuss this in the Committer Meeting? Likely we should refine the TRG a little bit. I was confused in the beginning and discussed it with @mhellmeier - we came to the KIT way conclusion :)

**Comment by matbmoser** [comment]
@tom-rm-meyer-ISST 
![image](https://github.com/user-attachments/assets/5f016de6-6cea-40b6-8c2b-bcb67a9a915f)

It really clear that the TRG is for KITs, not for product repositories.

But sure lets propose that in the committer meeting. I think is a good idea to have it also for the products 💯 

I will close this ticket then ;) :octocat:

**Comment by mhellmeier** [comment]
I think talking about it during the next office hour or at the Committer Meeting sounds good.
